### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [drkhsh/zsh-banner#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by drkhsh** [comment]
Uh, seems like I forgot that, fixed. Thanks.

**Comment by drkhsh** [comment]
Fixed in 6010787067e309a4169707be175f9e4879266293
